#!/usr/bin/env python3
#
# t1 -- send

import time
from random import choice
from random import randrange

import zmq

if __name__ == "__main__":
    stock_symbols = ['RAX', 'EMC', 'GOOG', 'AAPL', 'RHAT', 'AMZN']

    context = zmq.Context()
    socket = context.socket(zmq.PUB)

    socket.bind("epgm://eth0;239.1.1.1:5000")

    while True:
        time.sleep(3)
        # pick a random stock symbol
        stock_symbol = choice(stock_symbols)
        # set a random stock price
        stock_price = str(randrange(1, 100))

        stock_data = {
            'symbol': stock_symbol,
            'price': stock_price
        }

        print("Sending JSON Message: {0}".format(stock_data))

        # send the JSON message
        socket.send_json(stock_data)
