#! /usr/bin/env python3
#
# t1 Receiver


import zmq

if __name__ == "__main__":
    context = zmq.Context()
    socket = context.socket(zmq.SUB)
    socket.setsockopt_string(zmq.SUBSCRIBE, '')
    # Python3 Note: Use the below line and comment
    # the above line out
    # socket.setsockopt_string(zmq.SUBSCRIBE, '')
    # socket.connect('epgm://wlan0;239.192.1.1:5000')

    socket.connect("epgm://239.1.1.1:5000")

    while True:
        json_data = socket.recv_json()
        print("{0}".format(json_data))
        
