FROM resin/rpi-raspbian

MAINTAINER Mike Petonic <petonic@yahoo.com>

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libsodium-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y git build-essential libtool autoconf automake pkg-config unzip libkrb5-dev wget

#
# OpenPGM
#
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libpgm-dev

#
# libzmq 4.2.4
#

RUN cd /tmp && wget http://download.zeromq.org/zeromq-4.2.4.tar.gz && cd zeromq-4.2.4 && \
    ./autogen.sh && ./configure --with-pgm && make && \
         make install && ldconfig


#
# pyzmq
#
RUN apt-get install python-dev python3-dev
RUN apt-get install -y python-pip python3-pip
RUN python2 -m pip install pyzmq
RUN python3 -m pip install pyzmq
